### PR TITLE
Use gevent.pywsgi as default server, fixes #149

### LINKED ISSUE #149: Almost impossible to copy and move files on Windows
I never really had problems using Wsidav on a linux environment.
The thing is: I'm now using Windows and since official Windows Webdav doesn't work, I stick to wsgidav. I can open files without problems from a wsgidav mount point, but I can't copy files to a wsgidav folder. I just can't. Sometimes it says "No space left" which is not true since I got 80gb free on both source and destination folders.

I have this problem on Windows since version 2.x.x. I thought it would change when I've updated, but the same thing happens.
I'm using it with auth=anonymous since I don't know how to use authentication on Windows.

### PR DESCRIPTION
**Pull request by SteffenDE**
This is a suggestion for fixing #149, maybe you can find the related cheroot issue instead, but I'm mainly using gevent.pywsgi which performs quite well so far with Flask + WsgiDAV.

Use gevent instead of cheroot for serving wsgidav:
- implemented SSL support for gevent
- changed tests to use gevent instead of cheroot
- changed documentation

### CODE REVIEW

**Comment by SteffenDE** [comment]
Not quite sure why some tests are failing with `UserWarning: Unknown distribution option: 'executables'`. I just tried to use python3.7 as default...

**Comment by mar10** [comment]
Cool, that was fast.
I did a quick test on a Win10 box, copying a folder with images to WsgiDAV using FileExplorer and I still experienced [three 1 second pauses per file copy](https://github.com/mar10/wsgidav/issues/149#issuecomment-487288247).
It feels like the problem that would be fixed by disabling the 'Automatically detect settings' option, but I did this already. Maybe virus checker, DNS, ...
I will dig into this the next days, but if *you* see a File Explorer uploading a folder with many files as fast as macOS Finder can, there is hope ;-)

Did you run the WsgiDAV server on Windows? Do you see these pauses as well with cheroot, and it goes away with gevent?

**Comment by SteffenDE** [comment]
Yes. Server on macOS or Windows has the same effect. Totally smooth with gevent and **multi-second** pauses with cheroot:
gevent:
Bildschirmfoto 2019-05-13 um 23 33 33
cheroot:
Bildschirmfoto 2019-05-13 um 23 38 48
Also: the whole server is unresponsive during those delays, chrome does not receive a response:
Bildschirmfoto 2019-05-13 um 23 37 39

Seems like cheroot has an issue dealing with multiple requests at the same time? Maybe gevent does not experience those issues because of the monkey-patching + event loop design?

**Comment by SteffenDE** [comment]
To reproduce: I just downloaded the zip from the gevent_default branch and installed wsgidav into a virtualenv. Freshly installed python3.7, almost completely new Windows 10 VM. I just enabled BasicAuth for WebDAV for testing. The autodetect settings option is actually still checked. Works fine anyway.

**Comment by mar10** [comment]
I updated issue #149 with my latest findings. cheroot seems to behave ok, if we increase the thread size.
Gevents performs slightly better still (My slow gevent expreience was due to a local network issue).

I am building the MSI installer using cx_Freeze, which tends to make problems every now and then.
Currently it has problems to collect the dependencies for gevents, so we have to list them explicitly or somnethin like this happens:
```
2019-05-15 23:56:54.576 - <12076> wsgidav.wsgidav_app         WARNING :  Share '/:dir_browser' will allow anonymous read access.
Traceback (most recent call last):
  File "C:\prj\env\wsgidav_build_3.6\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
    module.run()
  File "C:\prj\env\wsgidav_build_3.6\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
    exec(code, m.__dict__)
  File "wsgidav/server/server_cli.py", line 829, in <module>
  File "wsgidav/server/server_cli.py", line 820, in run
  File "wsgidav/server/server_cli.py", line 494, in _run_gevent
  File "C:\prj\env\wsgidav_build_3.6\lib\site-packages\gevent\monkey.py", line 976, in patch_all
    patch_thread(Event=Event, _warnings=_warnings)
  File "C:\prj\env\wsgidav_build_3.6\lib\site-packages\gevent\monkey.py", line 178, in ignores
    return func(*args, **kwargs)
  File "C:\prj\env\wsgidav_build_3.6\lib\site-packages\gevent\monkey.py", line 572, in patch_thread
    _warnings=_warnings, _notify_did_subscribers=False)
  File "C:\prj\env\wsgidav_build_3.6\lib\site-packages\gevent\monkey.py", line 347, in _patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
  File "C:\prj\env\wsgidav_build_3.6\lib\site-packages\gevent\thread.py", line 40, in <module>
    from gevent.lock import BoundedSemaphore
  File "C:\prj\env\wsgidav_build_3.6\lib\site-packages\gevent\lock.py", line 7, in <module>
    from gevent._semaphore import Semaphore, BoundedSemaphore # pylint:disable=no-name-in-module,import-error
  File "C:\prj\env\wsgidav_build_3.6\lib\site-packages\gevent\_semaphore.py", line 12, in <module>
    locals()['AbstractLinkable'] = _get_linkable()
  File "C:\prj\env\wsgidav_build_3.6\lib\site-packages\gevent\_semaphore.py", line 10, in _get_linkable
    x = __import__('gevent._abstract_linkable')
ModuleNotFoundError: No module named 'gevent._abstract_linkable'
```

I only spent a few minutes so far, but until this is solved I hesitate to merge.

**Comment by mar10** [comment]
Btw. we *should* add your improvements (SSL support, 'Server' header, ...) in any case.
Do want to split this into a separate PR, so I can merge that and you don't loose kudos?

**Pull request closed without merging**
