### PR TITLE
Ensure owner property of lock manager is always bytes

### PR DESCRIPTION
**Pull request by pokoli**
This fixes the lock manager test for python2 and python3

### CODE REVIEW

**Comment by mar10** [comment]
Thanks, I will merge for now, but I guess we should review later if only bytestrings should be *accepted* by the API, so maybe re-add the test and fix the implementation, instead of avoiding it in the tests...

**Comment by pokoli** [comment]
> Thanks, I will merge for now, but I guess we should review later if only
> bytestrings should be /accepted/ by the API, so maybe re-add the test
> and fix the implementation, instead of avoiding it in the tests...
Thanks for merging, but I don't mind discussing the implementation before merging it. 

For me if it accepts an string this will be bytes for python2 and string (unicode) on python3. And this should be applicable on all the cases. 

But as I see you did some coding differences for python2 and python3 I imagined the implementation was correct.

**Comment by mar10** [comment]
We are testing methods like
```
LockManager._generateLock(principal, locktype, lockscope, lockdepth, lockowner, path, timeout)
```
which I guess should accept native strings on Pythons 2 and 3, so we can pass `lockowner="joe"`, (and not  `lockowner=b"joe"` on Py3).

I merged, because I was a bit in a hurry and was not really clear about this at that moment. Also, we are save as long as we are in the Py3 branch.
In the end, the litmus suite is reference (and real world clients), but my current feeling is that it should rather be fixed in the library code.

**Comment by mar10** [comment]
(and maybe we should stick to the current convention, using double quotes...)

**Pull request merged**
