### PR TITLE
Build on python:3-alpine using py-lxml native lib

### PR DESCRIPTION
**Pull request by fngx**

### CODE REVIEW

**Comment by mar10** [comment]
Thanks.
This seems to shrink the image to 10%, but are you sure that this makes lxml available?
I see this
```
PS C:\prj\git\wsgidav> docker run --rm -it -p 8080:8080 -v c:/temp:/var/wsgidav-root mar10/wsgidav
Running without configuration file.
14:59:09.619 - <140530954972040> wsgidav.wsgidav_app  INFO   :  Default encoding: utf-8 (file system: utf-8)
...
14:59:09.621 - <140530954972040> wsgidav              WARNING:  WARNING: Could not import lxml: using xml instead (slower). Consider installing lxml https://pypi.python.org/pypi/lxml.
...
14:59:09.726 - <140530954972040> wsgidav              INFO   :  Running WsgiDAV/2.4.1 Cheroot/6.4.0 Python/3.7.0
14:59:09.727 - <140530954972040> wsgidav              INFO   :  Serving on http://0.0.0.0:8080 ...
```

**Comment by fngx** [comment]
Sorry, did not check the logs, only runtime... I wasn't aware that it would fallback to xml.
By its look, seems that lxml will only ship for python 3.6. Latest alpine points to 3.7 so it wasn't going to find it.

This config is working without the warnings though, but it assumes that we run 3.6 :

```
FROM python:3.6-alpine

# Compilation dependencies for pip install lxml
RUN apk --no-cache add gcc libxslt-dev musl-dev # (alpine's glibc)

RUN pip install --no-cache-dir wsgidav cheroot lxml
RUN mkdir -p /var/wsgidav-root

EXPOSE 8080

CMD wsgidav --host 0.0.0.0 --port 8080 --root /var/wsgidav-root --no-config
```

Just advise me the way you would want it;  and if you prefer to always use latest python... then I can check further.

**Comment by mar10** [comment]
I assume that 3.7 would be a bit faster, but 3.6 would be cool enough, given that the image is so much smaller (travis and cx_freeze also still have problems with 3.7...).

**Comment by fngx** [comment]
Seems that latest `python:3-alpine` docker layer has been fixed and now compiles lxml correctly.
So now, I'm able to build everything using the following configuration :

https://github.com/fngx/wsgidav/pull/1/files

**Comment by fngx** [comment]
I think this issue can now be closed in favor of #126.

**Pull request closed without merging**
