### PR TITLE
Fix read chunks

### LINKED ISSUE #290: Unable to upload chunked big file using `requests` python library.
**Describe the bug**
I am trying to upload big files to this webdav server by using `requests` library. Other available libraries are not compatible with the way I receive the stream of data. However, the webdav server hangs forever and do not respond.

**To Reproduce**xx
1. Launch a webdav server `wsgidav --host=127.0.0.1 --port=31102 --root=/tmp --auth=anonymous`
2. Generate a big file `dd if=/dev/random of=data_big bs=1M count=100`
3. Upload it to the webdav server
```python
import requests
def generate():
    with open("data","rb") as f:
       while r:=f.read(1024**2):
          yield r
requests.put("http://127.0.0.1:31102/data", data=generate())
```
4. The upload hangs forever

**Expected behavior**

A working upload of the file.

**Screenshots, Log-Files, Stacktrace**
```
Running without configuration file.
13:54:26.097 - WARNING : App wsgidav.mw.cors.Cors(None).is_disabled() returned True: skipping.
13:54:26.101 - INFO    : WsgiDAV/4.2.0 Python/3.9.17 Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.28
13:54:26.102 - INFO    : Lock manager:      LockManager(LockStorageDict)
13:54:26.102 - INFO    : Property manager:  None
13:54:26.102 - INFO    : Domain controller: SimpleDomainController()
13:54:26.102 - INFO    : Registered DAV providers by route:
13:54:26.102 - INFO    :   - '/:dir_browser': FilesystemProvider for path '/root/.cache/pypoetry/virtualenvs/downloadservice-xTUGyw3C-py3.9/lib/python3.9/site-packages/wsgidav/dir_browser/htdocs' (Read-Only) (anonymous)
13:54:26.102 - INFO    :   - '/': FilesystemProvider for path '/tmp' (Read-Write) (anonymous)
13:54:26.102 - WARNING : Basic authentication is enabled: It is highly recommended to enable SSL.
13:54:26.103 - WARNING : Share '/' will allow anonymous write access.
13:54:26.103 - WARNING : Share '/:dir_browser' will allow anonymous read access.
13:54:26.103 - WARNING : Could not import lxml: using xml instead (up to 10% slower). Consider `pip install lxml`(see https://pypi.python.org/pypi/lxml).
13:54:26.145 - INFO    : Running WsgiDAV/4.2.0 Cheroot/10.0.0 Python 3.9.17
13:54:26.145 - INFO    : Serving on http://127.0.0.1:31102 ...
13:57:14.931 - DEBUG   : check_write_permission(/data, 0, [], )
13:57:14.931 - DEBUG   :   checking /
```

**Environment:**
Using the `python:3.9-slim-buster` docker image
```
WsgiDAV/4.2.0 Python/3.9.17(64 bit) Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.28
Python from: /usr/local/bin/python
```

Which WSGI server was used (cheroot, ext-wsgiutils, gevent, gunicorn, paste, uvicorn, wsgiref, ...)?

Which WebDAV client was used (MS File Explorer, MS Office, macOS Finder, WinSCP, Windows, file mapping, ...)? No official clients, the `requests` python library.

**Additional context**

Thanks you very much for your help.

### PR DESCRIPTION
**Pull request by Ph0tonic**
Hi,
This PR aims to fix #290.
I dug in the code to identify the cause of the problem and here is what I understood.
1. WSGI is a Python Web Server Gateway Interface defined here: https://peps.python.org/pep-0333/
2. When sending chunks the http specification defines how to encode content: https://datatracker.ietf.org/doc/html/rfc2616.html
3. The web server implementing WSGI is responsible for handling and decoding HTTP packets to comply with wsgi.

The issue I identified in the code is that `wsgidav` add an extra layer of packet decoding above the wsgi layer used to run the server (cheroot, ...). `wsgidav` should not try to decode chunks as they are already decoded and normalised by the wsgi server.

I just changed the decoding for `stream_data_chunked` but we might also want to refactor `stream_data`.
@mar10 Let me know if you have any questions.

### CODE REVIEW

**Comment by mar10** [comment]
Hi, thanks for your contribution and sorry for the slow response.
Did you test you changes with different WebDAV clients?

**Comment by Ph0tonic** [comment]
> Hi, thanks for your contribution and sorry for the slow response. Did you test you changes with different WebDAV clients?

Hi, no problem. No, I only tested it with python `requests` library.

PS: By the way I believe that the issue #282 is linked with this one.

**Comment by Ph0tonic** [comment]
Hi,
I tested the code with winscp and it worked.
I also simplified further the code.

**Comment by Ph0tonic** [comment]
Hi,
Any update on this ?

**Comment by mar10** [comment]
The previous code addressed existing problems and was configurable with `hotfixes.accept_put_without_content_length`.
For example #10 and #282.

Before we can merge, we need to make sure that the change does not introduce a regression.
Als we need to test at least with these clients:

- [ ] Windows 10/11 File Explorer
- [ ] Windows 10/11 Folder mapping
- [ ] macOS Finder
- [ ] MS Office (e.g. Word)

If we decide to merge, we also need to remove the hot fix flag and add `hotfixes.accept_put_without_content_length` to `_check_config()` as deprecated field.

**Comment by Ph0tonic** [comment]
Ok thanks, so I tested it with a windows environment but I am not able to test it with macOS Finder.
* [x]  Windows 10/11 File Explorer
* [x]  Windows 10/11 Folder mapping
* [ ]  macOS Finder
* [x]  MS Office (e.g. Word)

I also added the added field to the deprecated list.

**Comment by mar10** [comment]
Smoke test with Finder on macOS Ventura passed as well

**Comment by Ph0tonic** [comment]
Great ! Do you already have plans to release a new version ?

**Pull request merged**
