### PR TITLE
Allow dav providers to access the raw wsgi file object

### PR DESCRIPTION
**Pull request by SteffenDE**
I'm currently writing an app that allows uploading files using WebDAV. For file storage I'm using S3. boto3 has an api for uploading file like objects (`s3.upload_fileobj`) without reading everything into memory, therefore I need to access the raw wsgi file object from the dav provider:

```python
class FileResource(DAVNonCollection):
    ...
    def upload_fileobj(self, file):
            s3.upload_fileobj(file, "my-bucket", "my-filekey")
```

This is one of my first pull requests so you should rather see this as a suggestion. Maybe you even know a better solution for this problem.

Thanks for the great work!

### CODE REVIEW

**Comment by mar10** [comment]
There was a similar request a while ago: #48 would this help for your use case?

**Comment by SteffenDE** [comment]
Thank you, I looked at the stream_tools.py file, but the proposed solutions don't look quite as clean as just using the wsgi.input object. I thought about overwriting the do_PUT method, but as you already stated in #48, this is not trivial as "there [are] hotfixes for broken WebDAV clients and support for chunked transfer".
I tried the FileLikeQueue, but boto3 does not seem to like it:
```python
    def begin_write(self, content_type=None):
        """Open content as a stream for writing.
        See DAVResource.begin_write()
        """
        from wsgidav.stream_tools import FileLikeQueue
        queue = FileLikeQueue(max_size=1)
        import threading
        def worker():
            storage.upload(self.file, queue)
        t = threading.Thread(target=worker)
        t.setDaemon(True)
        t.start()
        return queue
```
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/steffen/Desktop/MonitorNews/monitornews-api/webdav/monitornews_dav_provider.py", line 345, in worker
    storage.upload(self.file, queue)
  File "/Users/steffen/Desktop/MonitorNews/monitornews-api/storage/S3Storage.py", line 105, in upload
    Config=TransferConfig(use_threads=False)
  File "/Users/steffen/Desktop/MonitorNews/monitornews-api/venv/lib/python3.7/site-packages/boto3/s3/inject.py", line 539, in upload_fileobj
    return future.result()
  File "/Users/steffen/Desktop/MonitorNews/monitornews-api/venv/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/Users/steffen/Desktop/MonitorNews/monitornews-api/venv/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/Users/steffen/Desktop/MonitorNews/monitornews-api/venv/lib/python3.7/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/Users/steffen/Desktop/MonitorNews/monitornews-api/venv/lib/python3.7/site-packages/s3transfer/upload.py", line 553, in _submit
    transfer_future, config):
  File "/Users/steffen/Desktop/MonitorNews/monitornews-api/venv/lib/python3.7/site-packages/s3transfer/upload.py", line 383, in requires_multipart_upload
    self._initial_data = self._read(fileobj, threshold, False)
  File "/Users/steffen/Desktop/MonitorNews/monitornews-api/venv/lib/python3.7/site-packages/s3transfer/upload.py", line 440, in _read
    return fileobj.read(amount)
  File "/Users/steffen/Desktop/MonitorNews/monitornews-api/venv/lib/python3.7/site-packages/wsgidav/stream_tools.py", line 72, in read
    res += compat.to_native(self.queue.get(True, 0.1))
  File "/Users/steffen/Desktop/MonitorNews/monitornews-api/venv/lib/python3.7/site-packages/wsgidav/compat.py", line 99, in to_native
    s = str(s, encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by mar10** [comment]
(I am a bit busy at the momen and don't have a test frame for this at hand, so it may take a bit until I can address this in depth.)

I am not sure if this was ever tested with Py3, so maybe there is a problem in the assumption that we want to handle it as native. Instead it probably should be binary streams?
Rather `self.unread = b""` and
```
res += compat.to_bytes(self.queue.get(True, 0.1))
```

**Comment by SteffenDE** [comment]
I finally found the time to address this issue and found the following solution:
```python
    def begin_write(self, content_type=None):
        """Open content as a stream for writing.
        See DAVResource.begin_write()
        """
        from webdav.flq import FileLikeQueue
        queue = FileLikeQueue()
        import threading
        def worker():
            storage.upload(self.file, queue)
        t = threading.Thread(target=worker)
        t.setDaemon(True)
        t.start()
        self.upload_thread = t
        return queue

    def end_write(self, with_errors):
        """Called when PUT has finished writing.
        This is only a notification. that MAY be handled.
        """
        if self.upload_thread:
            self.upload_thread.join()
            self.upload_thread = None
```

It is crucial to wait for the uploading thread to finish as the client will else try to access files that are not uploaded yet.
I had to write my own implementation of FileLikeQueue though, as the one bundled with wsgidav still does not seem to work with python3.

```python
from queue import SimpleQueue, Empty


class FileLikeQueue(object):
    """A queue for chunks that behaves like a file-like.

    read() and write() are typically called from different threads.

    This helper class is intended to handle use cases where an incoming PUT
    request should be directly streamed to a remote target:

    def begin_write(self, contentType=None):
        # Create a proxy buffer
        queue = FileLikeQueue(max_size=1)
        # ... and use it as source for the consumer:
        requests.post(..., data=queue)
        # pass it to the PUT handler as target
        return queue
    """

    def __init__(self):
        self.is_closed = False
        self.queue = SimpleQueue()
        self.unread = b""

    def read(self, size=0):
        print("read", size)
        """Read a chunk of bytes from queue.

        size = 0: Read next chunk (arbitrary length)
             > 0: Read one chunk of `size` bytes (or less if stream was closed)
             < 0: Read all bytes as single chunk (i.e. blocks until stream is closed)

        This method blocks until the requested size become available.
        However, if close() was called, '' is returned immediately.
        """
        res = self.unread
        self.unread = b""
        # Get next chunk, cumulating requested size as needed
        while res == b"" or size < 0 or (size > 0 and len(res) < size):
            try:
                # Read pending data, blocking if neccessary
                # (but handle the case that close() is called while waiting)
                res += self.queue.get(True, 0.1)
            except Empty:
                # There was no pending data: wait for more, unless close() was called
                if self.is_closed:
                    break
        # Deliver `size` bytes from buffer
        if size > 0 and len(res) > size:
            self.unread = res[size:]
            res = res[:size]
        # print("FileLikeQueue.read({}) => {} bytes".format(size, len(res)))
        return res

    def write(self, chunk):
        """Put a chunk of bytes (or an iterable) to the queue.

        May block if max_size number of chunks is reached.
        """
        if self.is_closed:
            raise ValueError("Cannot write to closed object")
        # print("FileLikeQueue.write(), n={}".format(len(chunk)))
        # Add chunk to queue (blocks if queue is full)
        if isinstance(chunk, bytes):
            self.queue.put(chunk)
        elif isinstance(chunk, str):
            self.queue.put(chunk.encode("utf-8"))
        else:  # if not a string, assume an iterable
            for o in chunk:
                if isinstance(o, bytes):
                    self.queue.put(o)
                elif isinstance(o, str):
                    self.queue.put(o.encode("utf-8"))
                else:
                    raise Exception("invalid type")

    def close(self):
        # print("FileLikeQueue.close()")
        self.is_closed = True
```

**Comment by mar10** [comment]
Thanks, I will opened this a new issue as a reminder that I should fix the FileLikeQueue

**Pull request closed without merging**
