### PR TITLE
Do not access optional domain_controller without check

### PR DESCRIPTION
**Pull request by ganwell**
Few lines below there is a check:

https://github.com/mar10/wsgidav/blob/ca90c210a815576b0e7e467905b49a8b4fb22580/wsgidav/wsgidav_app.py#L279-L282

### CODE REVIEW

**Review by mar10 — COMMENTED** [review]
Thanks for contributing.
I assume, when `domain_controller` is `None`, the share will be accessible by anonymous, so the hint should reflect that?
maybe 
```py
if not domain_controller or domain_controller.is_share_anonymous(share)
```
Could you check taht please?

**Comment by ganwell** [comment]
Hi, 

My PR is wrong and

```
if not domain_controller or domain_controller.is_share_anonymous(share)
```

is much better, but

1. The HTTPAuthenticator from wsgidav can't live without a domain-controller.
2. I have very different authentication-scheme and domain-controllers were a bad interface for that, so I wrote my own HTTPAuthenticator, My HTTPAuthenticator always assumes that the share is not anonymous.
3. Correct could would IMO be:

```python
if domain_controller:
    if domain_controller.is_share_anonymous(share):
        hint  = " (anonymous)"
    else:
        hint  = ""
else:
    hint = " (custom auth)"
```

Shall I change my PR accordingly? I currently just fake a domain-controller.

**Comment by mar10** [comment]
Ok, if it works for you.
(I might rework that code sometime in a later major release)

**Comment by mar10** [comment]
Are you still planning to update this PR?

**Comment by ganwell** [comment]
@mar10 Interesseting, I missed your feedback. I update...

**Comment by mar10** [comment]
Thanks!

**Pull request merged**
