### PR TITLE
Docker image reduction from 244MB to 66.4MB

### PR DESCRIPTION
**Pull request by marlluslustosa**
final image reduction from 244MB to 66.4MB

### CODE REVIEW

**Comment by mar10** [comment]
Thanks

**Comment by mar10** [comment]
Hi,
the latest tag-build failed. Any ideas?

```
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Switched to a new branch 'v3.0.2'
KernelVersion: 4.4.0-1060-aws
Components: [{u'Version': u'18.03.1-ee-3', u'Name': u'Engine', u'Details': {u'KernelVersion': u'4.4.0-1060-aws', u'Os': u'linux', u'BuildTime': u'2018-08-30T18:42:30.000000000+00:00', u'ApiVersion': u'1.37', u'MinAPIVersion': u'1.12', u'GitCommit': u'b9a5c95', u'Arch': u'amd64', u'Experimental': u'false', u'GoVersion': u'go1.10.2'}}]
Arch: amd64
BuildTime: 2018-08-30T18:42:30.000000000+00:00
ApiVersion: 1.37
Platform: {u'Name': u''}
Version: 18.03.1-ee-3
MinAPIVersion: 1.12
GitCommit: b9a5c95
Os: linux
GoVersion: go1.10.2
Starting build of index.docker.io/mar10/wsgidav:release-3.0.2...
Step 1/6 : FROM alpine:latest
---> cc0abc535e36
Step 2/6 : RUN apk --no-cache add py-lxml py-pip
---> Running in 8927455d4c1c
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/18) Installing libgpg-error (1.36-r2)
(2/18) Installing libgcrypt (1.8.5-r0)
(3/18) Installing xz-libs (5.2.4-r0)
(4/18) Installing libxml2 (2.9.10-r1)
(5/18) Installing libxslt (1.1.34-r0)
(6/18) Installing py3-lxml (4.4.2-r0)
(7/18) Installing libbz2 (1.0.8-r1)
(8/18) Installing expat (2.2.9-r1)
(9/18) Installing libffi (3.2.1-r6)
(10/18) Installing gdbm (1.13-r1)
(11/18) Installing ncurses-terminfo-base (6.1_p20191130-r0)
(12/18) Installing ncurses-terminfo (6.1_p20191130-r0)
(13/18) Installing ncurses-libs (6.1_p20191130-r0)
(14/18) Installing readline (8.0.1-r0)
(15/18) Installing sqlite-libs (3.30.1-r1)
(16/18) Installing python2 (2.7.16-r3)
(17/18) Installing py-setuptools (42.0.2-r0)
(18/18) Installing py2-pip (18.1-r0)
Executing busybox-1.31.1-r8.trigger
OK: 72 MiB in 32 packages
Removing intermediate container 8927455d4c1c
---> b6670af1a5a3
Step 3/6 : RUN pip install --no-cache-dir wsgidav cheroot lxml
---> Running in 3a68d0e68b87
Collecting wsgidav
Downloading https://files.pythonhosted.org/packages/db/73/efbfbf17c4a56bd507a8b9b47193e205d851350a8ade976f32a3a12c1f04/WsgiDAV-3.0.2-py2.py3-none-any.whl (170kB)
Collecting cheroot
...
https://files.pythonhosted.org/packages/12/a4/3e7366d0f5e75dcad7be88524c8cbd0f3a9fb1db243269550981740c57fe/jaraco.functools-2.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2->wsgidav)
Downloading https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz
Installing collected packages: PyYAML, json5, six, defusedxml, MarkupSafe, Jinja2, wsgidav, more-itertools, backports.functools-lru-cache, jaraco.functools, cheroot, lxml
Running setup.py install for PyYAML: started
Running setup.py install for PyYAML: finished with status 'done'
Running setup.py install for MarkupSafe: started
Running setup.py install for MarkupSafe: finished with status 'done'
Running setup.py install for lxml: started
Running setup.py install for lxml: finished with status 'error'
Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-bj0doM/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-6gfQXd/install-record.txt --single-version-externally-managed --compile:
Building lxml version 4.4.2.
Building without Cython.
ERROR: /bin/sh: xslt-config: not found
** make sure the development packages of libxml2 and libxslt are installed **
Using build configuration of libxslt
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/lxml
copying src/lxml/cssselect.py -> build/lib.linux-x86_64-2.7/lxml
copying src/lxml/builder.py -> build/lib.linux-x86_64-2.7/lxml
...
copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
running build_ext
building 'lxml.etree' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
creating build/temp.linux-x86_64-2.7/src/lxml
gcc -fno-strict-aliasing -Os -fomit-frame-pointer -g -DNDEBUG -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100000 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-x86_64-2.7/src/lxml/etree.o -w
unable to execute 'gcc': No such file or directory
Compile failed: command 'gcc' failed with exit status 1
creating tmp
cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitnV_it9.c -o tmp/xmlXPathInitnV_it9.o
unable to execute 'cc': No such file or directory
*********************************************************************************
Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
*********************************************************************************
error: command 'gcc' failed with exit status 1
----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-bj0doM/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-6gfQXd/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-bj0doM/lxml/
Removing intermediate container 3a68d0e
```

**Comment by marlluslustosa** [comment]
Hi, I think it's in the dependency line.
You can add this line just below #dependencies and to test again?

#dependencies
RUN apk --no-cache add py-lxml py-pip
**RUN apk --no-cache add gcc libxslt-dev musl-dev**

**Comment by mar10** [comment]
not yet there :-/
```
copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
running build_ext
building 'lxml.etree' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/src
creating build/temp.linux-x86_64-2.7/src/lxml
gcc -fno-strict-aliasing -Os -fomit-frame-pointer -g -DNDEBUG -Os -fomit-frame-pointer -g -DTHREAD_STACK_SIZE=0x100000 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/usr/include/libxml2 -Isrc -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-x86_64-2.7/src/lxml/etree.o -w
src/lxml/etree.c:97:10: fatal error: Python.h: No such file or directory
97 | #include "Python.h"
| ^~~~~~~~~~
compilation terminated.
Compile failed: command 'gcc' failed with exit status 1
creating tmp
cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /tmp/xmlXPathInitJUAgSE.c -o tmp/xmlXPathInitJUAgSE.o
/tmp/xmlXPathInitJUAgSE.c:2:1: warning: return type defaults to 'int' [-Wimplicit-int]
2 | main (int argc, char **argv) {
| ^~~~
cc tmp/xmlXPathInitJUAgSE.o -L/lib -lxml2 -o a.out
error: command 'gcc' failed with exit status 1
----------------------------------------
[91mCommand "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-y3MZro/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-OSF3PB/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-y3MZro/lxml/
[0m
Removing intermediate container f7a2302b84bd
The command '/bin/sh -c pip install --no-cache-dir wsgidav cheroot lxml' returned a non-zero code: 1
```

**Comment by marlluslustosa** [comment]
I received a PR in a personal repository that uses webdav. It solves that problem.
https://github.com/marlluslustosa/Floccus-WebDavDocker/pull/1

Changes:

FROM python:3-alpine

RUN apk add --no-cache --virtual .build-deps gcc libxslt-dev musl-dev py3-lxml py3-pip \
    && pip3 install wsgidav cheroot lxml \
    && apk del .build-deps gcc musl-dev

**Comment by mar10** [comment]
It compiles and runs now, thanks:
```
$ docker pull mar10/wsgidav
Using default tag: latest
latest: Pulling from mar10/wsgidav
...
Status: Downloaded newer image for mar10/wsgidav:latest
docker.io/mar10/wsgidav:latest
$ docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
mar10/wsgidav         latest              78e2ba392de0        45 minutes ago      101MB
...
$ docker run --rm -it -p 8080:8080 -v ./var/wsgidav-root mar10/wsgidav
...
2020-07-07 17:20:17.031 - <140300842675528> wsgidav                     INFO    :  Running WsgiDAV/3.0.3 Cheroot/8.3.0 Python/3.8.3
2020-07-07 17:20:17.032 - <140300842675528> wsgidav                     INFO    :  Serving on http://0.0.0.0:8080 ...
```

**Comment by marlluslustosa** [comment]
:P

**Pull request merged**
