### PR TITLE
better documentation for dir browsing

### PR DESCRIPTION
**Pull request by tworec**
I've made some comments to better guide users how to enable dir browsing

related to #144

### CODE REVIEW

**Comment by mar10** [comment]
Hi Piotr,
thanks for contributing!
I still have to find some time to check if this needs to be adjusted for the current 3.0.0 alpha version.
(If you are not aware of this version you may want try it as well. It introduces [some change to the config among others](https://github.com/mar10/wsgidav/blob/master/CHANGELOG.md) )

**Comment by tworec** [comment]
ok, feel free to reject this PR

**Comment by tworec** [comment]
I've tried `v3.0.0a7` but there are also surprises. Documentation does not say `RequestResolver` is mandatory middleware and must be at the end of the stack...

**Comment by mar10** [comment]
Thank you for taking the time. I am planning to release 3.0 sometime soon, and this kind of feedback helps a lot.

**Pull request merged**
